### ISSUE TITLE
Bug: Compilation fails

### ISSUE THREAD

**Issue by guilyx** [pucrs-automated-planning/adl2strips#1]
Hey all, 

I realize this isn't maintained but since pucrs seems relatively active I guess I'll still open an issue.

Make returns this:

```
In file included from scan-fct_pddl.y:593:0:
lex.fct_pddl.c: At top level:
lex.fct_pddl.c:877:26: error: macro "fct_pddlwrap" passed 1 arguments, but takes just 0
 extern int yywrap ( void );
```

Figured the fix was quite easy, will open a PR

**Comment by meneguzzi** [comment]
You got that one right! But hey, I appreciate your help anyhow!
